# This file is used to specify command line arguments to the docker run command
# rather than for replacing the Dockerfile.
web:
  build: .
  volumes:
    # We don't mount as read-only since our cache directory is inside
    - .:/usr/src/app/
  ports:
    - 80:80
  env_file: ./.env #place env vars in this file
  environment:
    - PYTHONUNBUFFERED=True #disable print buffering in gunicorn
    #- MODE=dev
    #- S3_BUCKET #define in .env file
    #- S3_ACCESS_KEY_ID #define in .env file
    #- S3_SECRET_ACCESS_KEY #define in .env file
  restart: always

