# This file is used to specify command line arguments to the docker run command
# rather than for replacing the Dockerfile.
web:
  build: .
  volumes:
    # We don't mount as read-only since our cache directory is inside
    - .:/usr/src/app/
  ports:
    - 80:80
  environment:
    - PYTHONUNBUFFERED=True #disable print buffering in gunicorn
    - MODE=dev
    - S3_BUCKET #define on command line
    - S3_ACCESS_KEY_ID #define on command line
    - S3_SECRET_ACCESS_KEY #define on command line

