---
- name: install docker
  sudo: yes
  hosts: default
  vars:
    docker_package: lxc-docker-1.6.1
    docker_compose_version: 1.2.0
  roles:
    - franklinkim.docker
    - franklinkim.docker-compose

- name: start app
  sudo: yes
  hosts: default
  #vars:
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: pull and run app
      docker:
        name: s3cache
        image: mikexstudios/s3cache
        state: reloaded #container is running and restarts when out of date
        pull: always #always check for newer version
        restart_policy: always
        ports:
          - 80:80
        volumes:
          - /tmp/s3cache:/usr/src/app/cache
        env:
          # Define these in vars/secrets.yml
          S3_ACCESS_KEY_ID: "{{ S3_ACCESS_KEY_ID }}"
          S3_SECRET_ACCESS_KEY: "{{ S3_SECRET_ACCESS_KEY }}"
          S3_BUCKET: "{{ S3_BUCKET }}"
