---
- name: install docker
  hosts: default
  sudo: yes
  vars:
    docker_package: lxc-docker-1.6.1
    docker_compose_version: 1.2.0
  roles:
    - franklinkim.docker
    - franklinkim.docker-compose

