# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = 'ubuntu/trusty64'
   
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # NOTE: Provider-specific configurations are intentionally commented out
  # in this file since each developer may have his/her own settings for RAM
  # and CPU. These settings should be set in the global Vagrantfile that
  # is located at ~/.vagrant.d/Vagrantfile.
  #
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = 'berks-cookbooks'
    chef.add_recipe 's3cache::default'
     
    # You may also specify custom JSON attributes:
    chef.json = {
      s3cache: {
        S3_BUCKET: ENV['S3_BUCKET'],
        S3_ACCESS_KEY_ID: ENV['S3_ACCESS_KEY_ID'],
        S3_SECRET_ACCESS_KEY: ENV['S3_SECRET_ACCESS_KEY'],
      }
    }
  end
end
